### ISSUE TITLE
Missing poster link

### ISSUE THREAD

**Issue by meandmytram** [oseledets/nla2020#1]
Hey @amkatrutsa, I've been recently going through the lectures (btw the notebooks are absolutely amazing) and I couldn't find a working link to a poster with matrix decompositions in Lecture 2. Can you please attach it?

**Comment by amkatrutsa** [comment]
Hello! The link is in the screenshot below and it works.
<img width="1162" alt="Screenshot 2021-10-12 at 09 51 58" src="https://user-images.githubusercontent.com/7030191/136906272-53660063-0ac3-4311-a9a6-9e461ed35038.png">
The poster also can be found here https://github.com/oseledets/nla2020/blob/main/decompositions.pdf

**Comment by meandmytram** [comment]
Thank you!
